config/routes.rb
Rails.application.routes.draw do
  resources :instructors do
    collection do
      get :search
    end
  end
  devise_for :users

  root 'home#index'
  get 'home/index'
  get 'contacts/index'
  get 'contacts/create'

  resources :users do
    resources :lessons
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :contacts, only: %i[index create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attributes :name,  validate: true
  attributes :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :contact,  validate: true
  attributes :message,  validate: true

  def headers
    {
      subject: 'Contact Form',
      to: 'macismail7@gmail.com',
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lessons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_detail

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:f_name, :l_name, :email, :phone_n, :password) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:f_name, :l_name, :email, :phone_n, :password, :current_password) }
  end

  def set_detail
    if user_signed_in?
      session[:f_name] = current_user.f_name
      session[:l_name] = current_user.l_name
      @userDetail = session[:f_name] + ' ' + session[:l_name]
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # before_action :set_post, only: [:index, :create]
  # before_action :authenticate_user!, except: %i[show index]
  # rails g migrate add_user_id_to_lessons user_id:integer
  def index
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'error sending message.'
      render 'index'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_cookie

  def set_cookie
    if user_signed_in?
      cookies[:f_name] = current_user.f_name
      @user_f_name = cookies[:f_name]
    end
  end

  def index; end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: %i[show edit update destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = if params[:search].blank?
                     Instructor.all
                   else
                     Instructor.where('LOWER(full_name) LIKE ?', "%#{params[:search].downcase}%")
                   end
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
    @instructor = Instructor.find(params[:id])
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit; end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_instructor
    @instructor = Instructor.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def instructor_params
    params.require(:instructor).permit(:full_name, :phone_n, :email, :category)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /lessons
  # GET /lessons.json
  def index
    # @lessons = current_user.lessons
    if params[:search].blank?
      @lessons = current_user.lessons
    else
      @lessons = current_user.lessons.where('LOWER(full_name) LIKE ?', "%#{params[:search].downcase}%")
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    require 'lesson_counter'

    # using decorator here to calculate the lessons remaining hours and total price
    hours_rmn = LessonsDecorator.new(@lesson.n_lesson, @lesson.duration)
    @remaining_h = hours_rmn.left_hours

    total_prc = LessonsDecorator.new(@lesson.n_lesson, 0)
    @total_p = total_prc.total_price

    # using singleton to display information message
    require 'singleton_file'

    conf = LessonStatus.instance
    st = conf.check_status(@remaining_h)
    @course_status = 'This is the last lesson' if st
  end

  # GET /lessons/new
  def new
    @lesson = current_user.lessons.build
  end

  # GET /lessons/1/edit
  def edit; end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = current_user.lessons.build(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to user_lesson_path(current_user, @lesson), notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to user_lesson_path(@lesson), notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to user_lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lesson
    @lesson = current_user.lessons.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def lesson_params
    params.require(:lesson).permit(:full_name, :l_date, :l_time, :n_lesson, :duration, :instructor, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact do |f| %>
  <div class="wrap-input100 validate-input" data-validate="Please enter your name">
    <%= f.text_field :name, class: "input100",  placeholder: "Full Name", required: true %>
    <span class="focus-input100"></span>
  </div>

  <div class="wrap-input100 validate-input" data-validate = "Please enter your email: e@a.x">
    <%= f.email_field :email, class: "input100", placeholder: "E-mail", required: true %>
    <span class="focus-input100"></span>
  </div>

  <div class="wrap-input100 validate-input" data-validate = "Please enter your phone">
    <%= f.text_field :contact, class: "input100", placeholder: "Phone", required: true %>
    <span class="focus-input100"></span>
  </div>

  <div class="wrap-input100 validate-input" data-validate = "Please enter your message">
    <%= f.text_area :message, class:"input100", placeholder: "Your Message", required: true %>
    <span class="focus-input100"></span>
  </div>

  <div class="container-contact100-form-btn">
    <%= f.submit 'send Message', class:"contact100-form-btn btn-outline-primary" %>
  </div>
<% end %>

app/views/contacts/create.html.erb
<div class="container">
  <h1>Contact Create</h1><hr>
  <h4 class="text-center" id="notice">Message deliverd Successfully</h4><br>
</div>

app/views/contacts/index.html.erb
<div class="container-contact100">

		<div class="wrap-contact100">
			<div class="contact100-form validate-form">
				<span class="contact100-form-title">
					Send Us A Message
				</span>
				<%= render 'form'%>
			</div>
		</div>
	</div>

app/views/home/index.html.erb
<div class="bg-img">
  <% if user_signed_in? %>
  <div class="text-center">
    <h4> Welcome <%= @user_f_name %></h4>
  </div>
  <% end %>
  <%= image_tag("car.png", :alt => "car feed", class:"img-fluid") %>
</div>

app/views/instructors/_form.html.erb
<%= form_with(model: instructor, local: true) do |form| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :full_name %><br>
    <%= form.text_field :full_name %>
  </div>

  <div class="form-group">
    <%= form.label :phone_nnmber %><br>
    <%= form.text_field :phone_n %>
  </div>

  <div class="form-group">
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>

  <div class="form-group">
    <%= form.label :category %><br>
    <%= form.text_field :category %>
  </div>

  <div class="control-group">
    <%= form.submit 'Submit', class:'btn btn-outline-primary btn-sm' %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<div class="row">
  <div class="col-3"></div>
  <div class="col-6">
    <div class="jumbotron text-center">
      <h1>Update Instructor</h1><hr>
      <div class="btn-group">
        <%= link_to 'Show', @instructor, class:'btn btn-outline-primary btn-sm' %>
        <%= link_to 'Back', instructors_path, class:'btn btn-outline-primary btn-sm' %>
      </div><br><br>
        <%= render 'form', instructor: @instructor %>
    </div>
  </div>
</div>

app/views/instructors/index.html.erb
<div class="container">
      <p id="notice"><%= notice %></p>

  <h1 class="text-center">Instructors</h1><br>
  <div class="row">
    <div class="col-7">
      <%= link_to 'New Instructor', new_instructor_path, class:'btn btn-outline-primary btn-sm' %>
    </div>
    <div class="col-5">
      <%= form_tag instructors_path, method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search..." %>
        <%= submit_tag "Search", class:'btn btn-outline-primary btn-sm' %>
      <% end %>
    </div>
  </div><br><br>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Full name</th>
        <th>Phone number</th>
        <th>Email</th>
        <th>Category</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @instructors.each do |instructor| %>
        <tr>
          <td><%= instructor.full_name %></td>
          <td><%= instructor.phone_n %></td>
          <td><%= instructor.email %></td>
          <td><%= instructor.category %></td>
          <div class="btn-group">
            <td><%= link_to 'Show', instructor, class:'btn btn-outline-primary btn-sm' %></td>
            <td><%= link_to 'Edit', edit_instructor_path(instructor), class:'btn btn-outline-primary btn-sm' %></td>
            <td><%= link_to 'Destroy', instructor, class:'btn btn-outline-primary btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </div>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/instructors/new.html.erb
<div class="container">
  <h1 class="text-center">New Instructor</h1><br>
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="jumbotron text-center">

      <%= link_to 'Back', instructors_path, class:'btn btn-outline-primary btn-sm' %>
        <hr><br>
      <%= render 'form', instructor: @instructor %>

      </div>
    </div>
  </div>
</div>

app/views/instructors/show.html.erb
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="jumbotron text-center">

        <h2>Instructor Details</h2><hr>

        <p id="notice"><%= notice %></p>

        <p>
          <strong>Full name:</strong>
          <%= @instructor.full_name %>
        </p>

        <p>
          <strong>Phone number:</strong>
          <%= @instructor.phone_n %>
        </p>

        <p>
          <strong>Email:</strong>
          <%= @instructor.email %>
        </p>

        <p>
          <strong>Category:</strong>
          <%= @instructor.category %>
        </p>
        <div class="btn-group">
          <%= link_to 'Back', instructors_path, class:'btn btn-outline-primary btn-sm' %>
        </div>

      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Motorschool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'partials/navbar'%>
    <div class="container">
      <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
          <p class="notice alert-success text-center"><%= notice %></p>
          <p><%= alert %></p>
        </div>
        <div class="col-2">
          <% if user_signed_in? %>
          <div class="text-center">
            <i><%= link_to @userDetail, edit_user_registration_path %></i>
          </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
    <%= render partial: "partials/datepicker" %>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_with(model: [current_user, lesson], local: true) do |form| %>
<% if lesson.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(lesson.errors.count, "error") %>
      prohibited this lesson from being saved:</h2>

    <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= form.label :Learner_full_name %><br>
  <%= form.text_field :full_name, class:'form-control' %>
</div>

<div class="form-group">
  <%= form.label :lesson_date %><br>
  <%= form.text_field :l_date, autofocus:true, class:'form-control datepicker' %>
</div>

<div class="form-group">
  <%= form.label :lesson_time %><br>
  <%= form.time_select :l_time, class:'form-control' %>
</div>

<div class="form-group">
  <%= form.label :remaining_hours %>
  <%= form.text_field :n_lesson, class:'form-control' %>
</div>

<div class="form-group">
  <%= form.label :duration %><br>
  <%= form.text_field :duration, class:'form-control' %>
</div>

<div class="control-group">
  <% form.label :instructor %><br>
  <% form.collection_select :instructor, Instructor.order(:full_name), :full_name, :full_name %>
</div>

<div class="form-group">
  <% form.label :user_id %>
  <% form.text_field :user_id %>
</div>

<div class="form-group text-center">
  <%= form.submit "Submit", class:'btn btn-outline-primary btn-sm' %>
</div>
<% end %>

app/views/lessons/edit.html.erb
<div class="container">
  <h1 class="text-center">Update Lesson</h1><br>
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="jumbotron">

      <%= link_to 'Show', user_lesson_path(current_user, @lesson), class:'btn btn-outline-primary btn-sm' %>
      <%= link_to 'Back', user_lessons_path, class:'btn btn-outline-primary btn-sm' %>
      <hr><br>
      <%= render 'form', lesson: @lesson %>

      </div>
    </div>
  </div>
</div>

app/views/lessons/index.html.erb
  <h2 class="text-center"><%= current_user.f_name %> Lessons</h2><hr>
  <h4 class="text-center" id="notice"><%= notice %></h4>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-4">
      <%= link_to 'New Lesson', new_user_lesson_path, class:'btn btn-outline-primary btn-sm' %>
    </div>
    <div class="col-6">
      <%= form_tag user_lessons_path, method: :get do %>
        <%= text_field_tag :search, params[:search], placeholder: "Learner Name..." %>
        <%= submit_tag "Search", class:'btn btn-outline-primary btn-sm' %>
      <% end %>
    </div>
  </div><br>
  <% n = 1 %>
  <div class="row">
    <% @lessons.each do |lesson| %>
    <div class="col-4">
      <div class="card bg-info rounded" style="width:300px">
        <div class="card-body text-center">
          <h4 class="card-title">Lesson <%= n %></h4><br>
          <p><b>leerner name: </b><%= lesson.full_name %></p>
          <p><b>lesson date: </b><%= lesson.l_date %></p>
          <p><b>time: </b><%= lesson.l_time.to_formatted_s(:time) %></p>
          <p><b>lesson duration: </b><%= lesson.duration %></p>
          <p><b></b><% lesson.instructor %></p>
          <div class="btn-group">
            <%= link_to 'Show', user_lesson_path(current_user, lesson), class:'btn btn-outline-primary sm' %>
            <%= link_to 'Edit', edit_user_lesson_path(current_user, lesson), class:'btn btn-outline-primary sm' %>
            <%= link_to 'Destroy', user_lesson_path(current_user, lesson), class:'btn btn-outline-primary sm', method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div><br>
    </div>
    <% n = n+1 %>
    <% end %>
  </div>

app/views/lessons/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="jumbotron">
        <h2 class="text-center">New Lesson</h2><br>
      <%= link_to 'Back', user_lessons_path, class:'btn btn-outline-primary btn-sm'  %>
        <hr>
      <%= render 'form', lesson: @lesson %>

      </div>
    </div>
  </div>
</div>

app/views/lessons/show.html.erb
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="jumbotron text-center">
        <h2>lesson details</h2><hr>

        <p id="notice"><%= notice %></p>

        <div class="btn-group">
          <%= link_to 'Edit', edit_user_lesson_path(@lesson), class:'btn btn-outline-primary btn-sm' %>
          <%= link_to 'Back', user_lessons_path, class:'btn btn-outline-primary btn-sm' %>
        </div>
        <br><br>
        <h4 class="notice alert-danger"><%= @course_status %></h4>

        <p> <b>Learner name:</b> <%= @lesson.full_name %> </p>

        <p> <b>User email:</b> <%= current_user.email %> </p>

        <p> <b>Lesson date:</b> <%= @lesson.l_date %> </p>

        <p> <b>time:</b> <%= @lesson.l_time.to_formatted_s(:time) %> </p>

        <p> <b>Duration:</b> <%= @lesson.duration %> </p>

        <p> <b>Total Hours:</b> <%= @lesson.n_lesson %> </p>

        <p> <b>Remaining Hours:</b> <%= @remaining_h %> </p>

        <p> <b></b> <% @lesson.instructor %> </p>

        <p> <b>Total Price:</b> <%= @total_p %> €</p>

      </div>
    </div>
  </div>

app/views/partials/_datepicker.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker({format: 'yyyy-mm-dd'});
  });
</script>

app/views/partials/_navbar.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Motor School', home_index_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample03">
      <ul class="navbar-nav md-auto"> <!--  menu left chage to ml-md-auto -->
        <% if user_signed_in? && current_user.email == 'admin@gmail.com' %>
        <li class="nav-item">
          <b><%= link_to 'instructors', instructors_path, class:'nav-link' %></b>
        </li>
        <%  end %>

        <% if user_signed_in? && current_user.email != 'admin@gmail.com' %>
        <li class="nav-item">
          <%= link_to 'lessons', user_lessons_path(current_user), class:"nav-link" %>
        </li>
        <%  end %>

        <li class="nav-item" style="padding-top:9px" >
          <%= link_to 'Test Info', 'http://www.rsa.ie/Documents/Learner%20Drivers/Preparing_driving_test_DL_v2.pdf', class:"nav-item" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Contact us', contacts_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
    <div class="collapse navbar-collapse" id="navbarsExample03">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'My Account', new_user_session_path, class:"nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>